version: '3.8'

services:
  app:
    build: .
    container_name: go-app
    ports:
      - '8080:8080'
    depends_on:
      - postgres
      - redis
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  postgres:
    image: postgres:17
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/seed.sql:/docker-entrypoint-initdb.d/seed.sql:ro
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - '6379:6379'

volumes:
  pgdata:
