package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.63

import (
	"context"

	"github.com/Diegoes7/meetups/models"
)

// Invitations is the resolver for the invitations field.
func (r *queryResolver) Invitations(ctx context.Context, filter *models.InvitationFilter, limit *int32, offset *int32) ([]*models.Invitation, error) {
	return r.Domain.GetInvitations(filter, limit, offset)
}
