package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.63

import (
	"context"

	"github.com/Diegoes7/meetups/models"
)

// SendMessage is the resolver for the sendMessage field.
func (r *mutationResolver) SendMessage(ctx context.Context, input models.NewMessageInput) (*models.Message, error) {
	return r.Domain.SendMessage(ctx, input)
}

// EditMessage is the resolver for the editMessage field.
func (r *mutationResolver) EditMessage(ctx context.Context, input models.UpdateMessageInput) (*models.Message, error) {
	return r.Domain.EditMessage(ctx, input)
}

// DeleteMessage is the resolver for the deleteMessage field.
func (r *mutationResolver) DeleteMessage(ctx context.Context, messageID string) (bool, error) {
	return r.Domain.DeleteMessage(ctx, messageID)
}

// GetMessagesByMeetup is the resolver for the getMessagesByMeetup field.
func (r *queryResolver) GetMessagesByMeetup(ctx context.Context, meetupID string, limit *int32, offset *int32) ([]*models.Message, error) {
	return r.Domain.MessageRepo.GetMessagesByMeetup(meetupID, limit, offset)
}
