// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

import (
	"time"
)

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type MeetupUpdate struct {
	MeetupID   string   `json:"meetupId"`
	Started    bool     `json:"started"`
	NewMessage *Message `json:"newMessage,omitempty"`
}

type MeetupsFilter struct {
	Name *string `json:"name,omitempty"`
}

type Message struct {
	ID        string    `json:"id"`
	Sender    *User     `json:"sender"`
	Content   string    `json:"content"`
	Timestamp time.Time `json:"timestamp"`
}

type Mutation struct {
}

type NewMeetup struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

type Query struct {
}

type RegisterArgs struct {
	Username        string `json:"username"`
	Email           string `json:"email"`
	Password        string `json:"password"`
	ConfirmPassword string `json:"confirmPassword"`
	FirstName       string `json:"firstName"`
	LastName        string `json:"lastName"`
}

type Subscription struct {
}

type TimeUnix struct {
	UnixTime  int32  `json:"unixTime"`
	TimeStamp string `json:"timeStamp"`
}

type UpdateMeetup struct {
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
}
